/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

/**
 *
 * @author Nazriel
 */
public class makanan extends javax.swing.JFrame {

    /**
     * Creates new form makanan
     */
    public makanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxSoto = new javax.swing.JCheckBox();
        jCheckBakso = new javax.swing.JCheckBox();
        jCheckSate = new javax.swing.JCheckBox();
        jCheckMie = new javax.swing.JCheckBox();
        jTextFieldSoto = new javax.swing.JTextField();
        jTextFieldBakso = new javax.swing.JTextField();
        jTextFieldSate = new javax.swing.JTextField();
        jTextFieldMie = new javax.swing.JTextField();
        jButtonHitung = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jLabelMenuMakanan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBoxSoto.setText("Soto Rp.17.000");
        jCheckBoxSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSotoActionPerformed(evt);
            }
        });

        jCheckBakso.setText("Bakso Rp.20000");
        jCheckBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBaksoActionPerformed(evt);
            }
        });

        jCheckSate.setText("Sate Rp.19000");
        jCheckSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckSateActionPerformed(evt);
            }
        });

        jCheckMie.setText("Mie Kocok Rp.20000");
        jCheckMie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckMieActionPerformed(evt);
            }
        });

        jTextFieldSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSotoActionPerformed(evt);
            }
        });

        jTextFieldBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBaksoActionPerformed(evt);
            }
        });

        jTextFieldSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSateActionPerformed(evt);
            }
        });

        jButtonHitung.setText("Hitung");
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jLabelMenuMakanan.setText("Total bayar");

        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckMie)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabelMenuMakanan))
                    .addComponent(jCheckSate)
                    .addComponent(jCheckBakso)
                    .addComponent(jCheckBoxSoto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBakso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldMie, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSoto)
                    .addComponent(jTextFieldSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBakso)
                    .addComponent(jTextFieldBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckSate)
                    .addComponent(jTextFieldSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckMie)
                    .addComponent(jTextFieldMie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHitung)
                    .addComponent(jButtonHapus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMenuMakanan)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBaksoActionPerformed
        // TODO add your handling code here:
        if (jCheckBakso.isSelected()==true){
            jTextFieldBakso.setEditable(true);
        }
        else{
            jTextFieldBakso.setEditable(false);
            jTextFieldBakso.setText("");
        }
    }//GEN-LAST:event_jCheckBaksoActionPerformed

    private void jTextFieldBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBaksoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBaksoActionPerformed

    private void jTextFieldSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSateActionPerformed

    private void jCheckBoxSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSotoActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxSoto.isSelected()==true){
            jTextFieldSoto.setEditable(true);
        }
        else{
            jTextFieldSoto.setEditable(false);
            jTextFieldSoto.setText("");
        }
    }//GEN-LAST:event_jCheckBoxSotoActionPerformed

    private void jTextFieldSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSotoActionPerformed

    private void jCheckSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckSateActionPerformed
        // TODO add your handling code here:
        if (jCheckSate.isSelected()==true){
            jTextFieldSate.setEditable(true);
        }
        else{
            jTextFieldSate.setEditable(false);
            jTextFieldSate.setText("");
        }
    }//GEN-LAST:event_jCheckSateActionPerformed

    private void jCheckMieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckMieActionPerformed
        // TODO add your handling code here:
        if (jCheckMie.isSelected()==true){
            jTextFieldMie.setEditable(true);
        }
        else{
            jTextFieldMie.setEditable(false);
            jTextFieldMie.setText("");
        }
    }//GEN-LAST:event_jCheckMieActionPerformed

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        // TODO add your handling code here:
        int total = 0;
        if (jCheckBoxSoto.isSelected()){
            String soto = jTextFieldSoto.getText();
            int jumlahSoto = Integer.parseInt(soto);
            int hargaSoto = jumlahSoto * 5000;
            total = total + hargaSoto;
        }
        if (jCheckBakso.isSelected()){
            String Bakso = jTextFieldBakso.getText();
            int jumlahBakso = Integer.parseInt(Bakso);
            int hargaBakso = jumlahBakso * 7000;
            total = total + hargaBakso;
        }
        if (jCheckSate.isSelected()){
            String Sate = jTextFieldSate.getText();
            int jumlahSate = Integer.parseInt(Sate);
            int hargaSate = jumlahSate * 8000;
            total = total + hargaSate;
        }
        if (jCheckMie.isSelected()){
            String Mie = jTextFieldMie.getText();
            int jumlahMie = Integer.parseInt(Mie);
            int hargaMie = jumlahMie * 8000;
            total = total + hargaMie;
        }
        jTextFieldTotal.setText(""+total);
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        jTextFieldSoto.setEditable(false);
        jTextFieldSoto.setText("");
        jTextFieldBakso.setEditable(false);
        jTextFieldBakso.setText("");
        jTextFieldSate.setEditable(false);
        jTextFieldSate.setText("");
        jTextFieldMie.setEditable(false);
        jTextFieldMie.setText("");
        
    }//GEN-LAST:event_jButtonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JCheckBox jCheckBakso;
    private javax.swing.JCheckBox jCheckBoxSoto;
    private javax.swing.JCheckBox jCheckMie;
    private javax.swing.JCheckBox jCheckSate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMenuMakanan;
    private javax.swing.JTextField jTextFieldBakso;
    private javax.swing.JTextField jTextFieldMie;
    private javax.swing.JTextField jTextFieldSate;
    private javax.swing.JTextField jTextFieldSoto;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
